# Generated by Django 4.2 on 2026-04-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(default="Anonymous", max_length=100),
            preserve_default=False,
        ),
    ]
